<div class="container mycontainer">
  <header class="footer">
    <div class="row myrowmenu align-items-center">
      <div class="col-3">
        <p>ALBERT LOPES
        
      </div>
      <div class="col-9">
        <nav class="menu">
          <ul>
            <li><a href="index.php" style="text-decoration:none">Photography</a></li>
            <li><a href="video.php" style="text-decoration:none">Video</a></li>
            <li><a href="about.php" style="text-decoration:none">About</a></li>
            <li><a href="form.php" style="text-decoration:none">Contact</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
</div>
